// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Yt23dZqNGc8dVB9-OcVEbI9_HYdonNg',
    appId: '1:834760977199:web:0d7d7016722bf1c6c00fda',
    messagingSenderId: '834760977199',
    projectId: 'easy-chat-cf74b',
    authDomain: 'easy-chat-cf74b.firebaseapp.com',
    storageBucket: 'easy-chat-cf74b.appspot.com',
    measurementId: 'G-FEN0QN6MTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDONVywtHj42_HaRKyxRlLxixRjCCWDt1w',
    appId: '1:834760977199:android:9a3306d8ca19e6f5c00fda',
    messagingSenderId: '834760977199',
    projectId: 'easy-chat-cf74b',
    storageBucket: 'easy-chat-cf74b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvO10r9PPdJUjEY0ye8Jvg6CPH0TSi1Fo',
    appId: '1:834760977199:ios:becd07893594a9bcc00fda',
    messagingSenderId: '834760977199',
    projectId: 'easy-chat-cf74b',
    storageBucket: 'easy-chat-cf74b.appspot.com',
    iosBundleId: 'com.example.easyChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvO10r9PPdJUjEY0ye8Jvg6CPH0TSi1Fo',
    appId: '1:834760977199:ios:8eed229fb225848dc00fda',
    messagingSenderId: '834760977199',
    projectId: 'easy-chat-cf74b',
    storageBucket: 'easy-chat-cf74b.appspot.com',
    iosBundleId: 'com.example.easyChat.RunnerTests',
  );
}
